# Author: Satya Patnaik
# Created: 20-March-2020
# L1 test for checking Navigator command after closing and opening new model.
settings:
  name: NavigatorSettingsUI
  description: Test the Navigator toggle UI in Visual Settings dialog.
  classname: L1
  suite: Navigator
  file: NavigatorSettingsUI.yaml
  exclusions:
    - desktop
    - ios
    - android
calls:
- command: GVCLoadModel
  input:
    - model:
      - UtilityTestModel
      - https://argo.hexagonppm.com/graphicsamples/utility/
      - parametrics
      - file
# Test
- command: ToggleNavigator
  input: 
    - false
  validation:
    - command: getnavigatorenabled
      expected: false
- command: MCDCloseModel
  input:
    - "UtilityTestModel"
- command: GVCLoadModel
  input:
    - model:
      - RefiningTestModel
      - https://argo.hexagonppm.com/graphicsamples/refining/
      - parametrics
      - file
  validation:
    - command: getnavigatorenabled
      expected: false
- command: ToggleNavigator
  input: 
    - true